server:
  port: 8000

eureka:
  client:
    fetch-registry: true # 유레카 클라이언트 활성화
    register-with-eureka: true # 유레카 클라이언트 활성화
    service-url:
      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
#          uri: http://localhost:64412 # 포워딩할 주소, http://localhost:8000/user 로 들어오면 http://localhost:64412 로 포워딩
          predicates:
            - Path=/user/** # 해당 gateway 서버의 /user/** 로 들어오는 요청은 user-service 로 인식하겠다는 조건
#            - After=2017-01-20T17:42:47.789-07:00 # 2017 이후 요청만 받음
#            - Cookie=valid, kakao
#            - Method=GET
          filters:
#            - AddRequestHeader=token, 123456
#            - AddResponseHeader=authenticated, yes
            - RewritePath=/user/(?<path>.*),/$\{path} # RewritePath
            - CustomAuthFilter # custom filter


        - id: order-service
          uri: lb://ORDER-SERVICE
#          uri: http://locahost:64413 # 포워딩할 주소, http://localhost:8000/order 로 들어오면 http://localhost:64413 로 포워딩
          predicates:
            - Path=/order/** # 해당 gateway 서버의 /order/** 로 들어오는 요청은 order-service 로 인식하겠다는 조건
#            - Before=2017-01-20T17:42:47.789-07:00 # 2017 이전 요청만 받음
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver] # Between 예제
#            - Cookie=valid, naver
#            - Method=POST
          filters:
            - RewritePath=/order/(?<path>.*),/$\{path}