server:
  port: 64413

spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: order-microservice-instance # 유레카가 인식할 instance id 인데 대시보드에서 식별하는 용도로 사용

  client:
    register-with-eureka: true # 해당 서비스가 클라이언트로 인식되어야 하므로
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # eureka server가 위치하고 있는 기본 주소, Camel Case 로 적어야 한다고 Spring Cloud Eureka 에 나와 있음