server:
  port: 8761 # 유레카 서버가 동작되는 서버의 포트를 지정, 보통 8761 포트를 많이 사용

spring:
  application:
    name: discovery-service # application name, 앞으로 모든 서비스를 application.name 으로 식별
eureka:
  client:
    register-with-eureka: false # 해당 서버를 클라이언트로 동작시키겠냐는 설정, false 로 설정
    fetch-registry: false # true로 지정시 자신을 디스커버리에 등록하게 됨
