server:
  port: 8761 # ??? ??? ???? ??? ??, 8761? ?? ??

spring:
  application:
    name: discovery-service # application name, ??? ?? ???? application.name ?? ??
eureka:
  client:
    register-with-eureka: false #?? ??? ?????? ?? ????? ??
    fetch-registry: false # true? ???? ??? ?????? ???? ?
